[package]
name = "lapdev-kube-rpc"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
tarpc.workspace = true
serde.workspace = true
k8s-openapi.workspace = true
lapdev-common.workspace = true
